services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health | grep '\"status\": \"UP\"'"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
